
url: 'http://ozangunalp.github.io'
baseurl: ''


# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Ozan Gunalp
tagline: R&D Software Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
website: ozan.gun-alp.com
linkedin: ozangunalp
github: ozangunalp
twitter: '@ozangunalp'

